apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-filters-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-filters
  template:
    metadata:
      labels:
        app: image-filters
    spec:
      containers:
        - image: eu.gcr.io/modified-badge-260712/image-filters:v10
          name: image-filters
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: gcloud
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://34.76.167.182:8085
          ports:
            - containerPort: 8085
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: image-filters
spec:
  type: ClusterIP
  ports:
    - port: 8085
      protocol: TCP
      targetPort: server
  selector:
    app: image-filters