kumuluzee:
  name: image-filter-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000