kumuluzee:
  name: image-filter-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://image-filters:8080
    http:
      port: 8080
  config:
    etcd:
      hosts: http://192.168.29.109:2379
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379
